class SeedData {



    masterProductAttribute = [
        { "id": 1, "name": "Color" },
        { "id": 2, "name": "Material" },
        { "id": 3, "name": "Storage Capacity" },
        { "id": 4, "name": "RAM" },
        { "id": 5, "name": "Display Size" },
        { "id": 6, "name": "Resolution" },
        { "id": 7, "name": "Connectivity" },
        { "id": 8, "name": "Battery Life" },
        { "id": 9, "name": "Weight" },
        { "id": 10, "name": "Warranty" },
        { "id": 11, "name": "Operating System" },
        { "id": 12, "name": "Processor" },
        { "id": 13, "name": "Charging Port" },
        { "id": 14, "name": "Refresh Rate" },
        { "id": 15, "name": "Water Resistance" },
        { "id": 16, "name": "Fabric Type" },
        { "id": 17, "name": "Country of Origin" },
        { "id": 18, "name": "Package Type" },
        { "id": 19, "name": "Voltage" },
        { "id": 20, "name": "Fragility" },
        { "id": 21, "name": "Model Year" },
        { "id": 22, "name": "Age Group" },
        { "id": 23, "name": "Gender" },
        { "id": 24, "name": "Sleeve Length" },
        { "id": 25, "name": "Fit Type" },
        { "id": 26, "name": "Pattern" },
        { "id": 27, "name": "Neckline" },
        { "id": 28, "name": "GPU / Graphics Card" },
        { "id": 29, "name": "Storage Type" },
        { "id": 30, "name": "Screen Panel Type" },
        { "id": 31, "name": "Assembly Required" },
        { "id": 32, "name": "Dimensions" },
        { "id": 33, "name": "Max Weight Capacity" },
        { "id": 34, "name": "Finish" },
        { "id": 35, "name": "Power Source" },
        { "id": 36, "name": "Storage Temperature" },
        { "id": 37, "name": "Allergen Information" },
        { "id": 38, "name": "Ingredients" },
        { "id": 39, "name": "Nutritional Grade" },
        { "id": 40, "name": "Volume" },
        { "id": 41, "name": "Skin Type Compatibility" },
        { "id": 42, "name": "Hair Type Compatibility" },
        { "id": 43, "name": "Fragrance Notes" },
        { "id": 44, "name": "Hazmat Class" },
        { "id": 45, "name": "IP Rating" },
        { "id": 46, "name": "Bluetooth Version" },
        { "id": 47, "name": "Number of Ports" },
        { "id": 48, "name": "Closure Type" },
        { "id": 49, "name": "Brand Tier" },
        { "id": 50, "name": "Software Compatibility" },
        { "id": 51, "name": "Mounting Type" },
        { "id": 52, "name": "Number of Channels" },
        { "id": 53, "name": "Sensor Type" },
        { "id": 54, "name": "Max Speed / RPM" },
        { "id": 55, "name": "Torque" },
        { "id": 56, "name": "Lens Type" },
        { "id": 57, "name": "Aperture" },
        { "id": 58, "name": "Occasion" },
        { "id": 59, "name": "Certification" },
        { "id": 60, "name": "Shelf Life" }
    ];

};

export default SeedData;